import type { Bit } from "./digital";
import type { TopicId } from "./topics";

export type McqTask = {
  id: string;
  topic: TopicId;
  kind: "mcq";
  question: string;
  options: string[];
  correct: number;
  explain: string;
};

export type BitsTask = {
  id: string;
  topic: TopicId;
  kind: "bits";
  question: string;
  labels: string[];
  correct: Bit[];
  explain: string;
};

export type Task = McqTask | BitsTask;

export const TASKS: Task[] = [
  {
    id: "gates-1",
    topic: "gates",
    kind: "mcq",
    question: "Чому дорівнює вихід NAND, якщо A=1 і B=1?",
    options: ["0", "1", "Z (високий імпеданс)", "невизначено"],
    correct: 0,
    explain: "NAND — інверсія AND. 1·1 = 1, інверсія дає 0.",
  },
  {
    id: "gates-2",
    topic: "gates",
    kind: "bits",
    question: "Заповніть вихід XOR для комбінацій AB = 00, 01, 10, 11.",
    labels: ["00", "01", "10", "11"],
    correct: [0, 1, 1, 0],
    explain: "XOR = 1, коли входи різні: 01 і 10.",
  },
  {
    id: "gates-3",
    topic: "gates",
    kind: "mcq",
    question: "Який базис є функціонально повним сам по собі?",
    options: ["лише AND", "лише XOR", "NAND", "лише OR"],
    correct: 2,
    explain: "З NAND (або з NOR) можна зібрати AND, OR і NOT — а отже будь-яку функцію.",
  },
  {
    id: "gates-4",
    topic: "gates",
    kind: "mcq",
    question: "Чому дорівнює NOR(0, 0)?",
    options: ["0", "1", "X", "той самий, що AND(0,0)"],
    correct: 1,
    explain: "OR(0,0)=0, інверсія дає 1. Це єдина одиниця в таблиці NOR.",
  },
  {
    id: "gates-5",
    topic: "gates",
    kind: "mcq",
    question: "Закон де Моргана: інверсія AND дорівнює…",
    options: ["AND інверсних входів", "OR інверсних входів", "XOR входів", "повторенню AND"],
    correct: 1,
    explain: "Ā·B̅ = A̅ + B̅. Інверсія добутку — сума інверсій.",
  },
  {
    id: "ff-1",
    topic: "flipflops",
    kind: "mcq",
    question: "Для асинхронного RS на NOR комбінація S=1, R=1 є…",
    options: ["записом 1", "записом 0", "зберіганням", "забороненою"],
    correct: 3,
    explain: "Обидва виходи NOR падають у 0. Після зняття входів стан непередбачуваний.",
  },
  {
    id: "ff-2",
    topic: "flipflops",
    kind: "mcq",
    question: "D-тригер по фронту CLK записує в Q…",
    options: ["інверсію D", "значення D", "Q ⊕ D", "завжди 1"],
    correct: 1,
    explain: "Q⁺ = D. Саме тому регістри будують на D-тригерах.",
  },
  {
    id: "ff-3",
    topic: "flipflops",
    kind: "mcq",
    question: "JK-тригер, J=1, K=1, був Q=1. Після фронту CLK Q дорівнює…",
    options: ["0", "1", "X", "залишається 1"],
    correct: 0,
    explain: "J=K=1 перемикає (toggle): Q⁺ = Q̅, з 1 буде 0.",
  },
  {
    id: "ff-4",
    topic: "flipflops",
    kind: "mcq",
    question: "T-тригер при T=0 по фронту CLK…",
    options: ["інвертує Q", "скидає Q", "зберігає Q", "встановлює Q=1"],
    correct: 2,
    explain: "Q⁺ = Q ⊕ T. Якщо T=0, Q не змінюється.",
  },
  {
    id: "ff-5",
    topic: "flipflops",
    kind: "mcq",
    question: "Чим синхронний тригер відрізняється від RS-защіпки?",
    options: [
      "не має інверсного виходу",
      "змінює стан лише по такту",
      "зберігає два біти",
      "працює лише з NAND",
    ],
    correct: 1,
    explain: "Защіпка прозора для входів увесь час; синхронний FF фіксує дані по фронту CLK.",
  },
  {
    id: "reg-1",
    topic: "registers",
    kind: "bits",
    question: "Регістр Q=1011, режим SHR, SI=0. Після такту Q3…Q0 = ?",
    labels: ["Q3", "Q2", "Q1", "Q0"],
    correct: [0, 1, 0, 1],
    explain: "Зсув управо: SI заходить у Q3, Q3→Q2, Q2→Q1, Q1→Q0. 1011 → 0101.",
  },
  {
    id: "reg-2",
    topic: "registers",
    kind: "mcq",
    question: "Паралельне завантаження 4-бітного регістра потребує…",
    options: ["4 тактів", "1 такту", "8 тактів", "стільки, скільки одиниць у слові"],
    correct: 1,
    explain: "Усі D-тригери мають спільний CLK: слово записується за один імпульс.",
  },
  {
    id: "reg-3",
    topic: "registers",
    kind: "bits",
    question: "Q=0110, режим SHL, SI=1. Після такту?",
    labels: ["Q3", "Q2", "Q1", "Q0"],
    correct: [1, 1, 0, 1],
    explain: "Зсув уліво: Q3 втрачається, SI заходить у Q0. 0110 → 1101.",
  },
  {
    id: "reg-4",
    topic: "registers",
    kind: "mcq",
    question: "Скільки D-тригерів у 8-бітному регістрі?",
    options: ["2", "4", "8", "16"],
    correct: 2,
    explain: "Один тригер — один біт. Ємність регістра = кількість тригерів.",
  },
  {
    id: "reg-5",
    topic: "registers",
    kind: "mcq",
    question: "Режим HOLD на такті означає…",
    options: ["обнулення", "Q⁺ = Q", "зсув на 1", "запис інверсії"],
    correct: 1,
    explain: "Тактовий імпульс є, але селектор режиму залишає старе слово.",
  },
  {
    id: "cnt-1",
    topic: "counters",
    kind: "bits",
    question: "Двійковий лічильник UP, Q=1111. Після такту (mod 16)?",
    labels: ["Q3", "Q2", "Q1", "Q0"],
    correct: [0, 0, 0, 0],
    explain: "15+1 = 16 ≡ 0 (mod 16). Переповнення обнуляє всі розряди.",
  },
  {
    id: "cnt-2",
    topic: "counters",
    kind: "bits",
    question: "DOWN, Q=0000. Після такту (4 біти)?",
    labels: ["Q3", "Q2", "Q1", "Q0"],
    correct: [1, 1, 1, 1],
    explain: "0−1 у модулі 16 дає 15, тобто 1111.",
  },
  {
    id: "cnt-3",
    topic: "counters",
    kind: "mcq",
    question: "Модуль 4-бітного двійкового лічильника дорівнює…",
    options: ["4", "8", "10", "16"],
    correct: 3,
    explain: "Модуль 2ⁿ. Для n=4 це 16 різних кодів: 0000…1111.",
  },
  {
    id: "cnt-4",
    topic: "counters",
    kind: "mcq",
    question: "Якщо Enable=0, а Reset=0, по фронту CLK лічильник…",
    options: ["додає 1", "скидається", "зберігає Q", "інвертує всі біти"],
    correct: 2,
    explain: "Без дозволу лічби стан утримується. Reset має пріоритет, але тут він 0.",
  },
  {
    id: "cnt-5",
    topic: "counters",
    kind: "mcq",
    question: "Частота на виході Q3 4-бітного лічильника (від f_clk) — це…",
    options: ["f/2", "f/4", "f/8", "f/16"],
    correct: 3,
    explain: "Кожен розряд ділить частоту навпіл. Q3 — старший, поділ на 16.",
  },
  {
    id: "enc-1",
    topic: "encoders",
    kind: "bits",
    question: "Пріоритетний 8→3. Активний лише I5. Код Y2 Y1 Y0?",
    labels: ["Y2", "Y1", "Y0"],
    correct: [1, 0, 1],
    explain: "5 = 101₂. Шифратор видає номер активного входу.",
  },
  {
    id: "enc-2",
    topic: "encoders",
    kind: "mcq",
    question: "Пріоритетний шифратор, одночасно I1=1 і I3=1. Хто перемагає?",
    options: ["I1, код 001", "I3, код 011", "сума кодів 100", "заборонена комбінація"],
    correct: 1,
    explain: "Більший номер має вищий пріоритет. I3 > I1, код 011.",
  },
  {
    id: "enc-3",
    topic: "encoders",
    kind: "mcq",
    question: "Навіщо вихід GS (valid) у пріоритетного шифратора?",
    options: [
      "інверсія коду",
      "відрізнити «немає входу» від коду 0",
      "такт",
      "перенесення в старший корпус",
    ],
    correct: 1,
    explain: "Коли всі Ii=0, код теж 000. GS=0 сигналізує, що це не I0.",
  },
  {
    id: "enc-4",
    topic: "encoders",
    kind: "bits",
    question: "Активний лише I0. Код 8→3?",
    labels: ["Y2", "Y1", "Y0"],
    correct: [0, 0, 0],
    explain: "Номер 0. Від «тиші» це відрізняє GS=1.",
  },
  {
    id: "enc-5",
    topic: "encoders",
    kind: "mcq",
    question: "Скільки виходів коду в шифратора 8→3?",
    options: ["2", "3", "8", "16"],
    correct: 1,
    explain: "⌈log₂ 8⌉ = 3 біти, плюс окремо можна мати GS.",
  },
  {
    id: "dec-1",
    topic: "decoders",
    kind: "bits",
    question: "Дешифратор 2→4, A1A0=10, E=1. Виходи Y0 Y1 Y2 Y3?",
    labels: ["Y0", "Y1", "Y2", "Y3"],
    correct: [0, 0, 1, 0],
    explain: "Адреса 2 вмикає лише Y2. Це one-hot.",
  },
  {
    id: "dec-2",
    topic: "decoders",
    kind: "mcq",
    question: "Якщо Enable=0, виходи дешифратора…",
    options: ["усі 1", "усі 0", "повторюють адресу", "інверсія адреси"],
    correct: 1,
    explain: "Строб гасить корпус. Так каскадують кілька 3→8 у 4→16.",
  },
  {
    id: "dec-3",
    topic: "decoders",
    kind: "mcq",
    question: "Дешифратор 3→8 має виходів…",
    options: ["3", "6", "8", "16"],
    correct: 2,
    explain: "2³ = 8 ліній. Кожна адреса вмикає рівно одну.",
  },
  {
    id: "dec-4",
    topic: "decoders",
    kind: "bits",
    question: "2→4, адреса 01, E=1. Y0…Y3?",
    labels: ["Y0", "Y1", "Y2", "Y3"],
    correct: [0, 1, 0, 0],
    explain: "01₂ = 1, активний Y1.",
  },
  {
    id: "dec-5",
    topic: "decoders",
    kind: "mcq",
    question: "Типове застосування дешифратора в памʼяті — це…",
    options: ["зсув слова", "вибір рядка/комірки за адресою", "порівняння тегів", "тактовий буфер"],
    correct: 1,
    explain: "Адреса дешифрується в одну лінію word-line.",
  },
  {
    id: "cmp-1",
    topic: "comparators",
    kind: "mcq",
    question: "A=1000, B=0111 (беззнакові 4 біти). Результат?",
    options: ["A<B", "A=B", "A>B", "невизначено"],
    correct: 2,
    explain: "8 > 7. Старший біт A одиниця, у B — нуль, далі можна не дивитись.",
  },
  {
    id: "cmp-2",
    topic: "comparators",
    kind: "bits",
    question: "A=0101, B=0101. Прапорці gt, eq, lt?",
    labels: ["A>B", "A=B", "A<B"],
    correct: [0, 1, 0],
    explain: "Порозрядна рівність. Лише eq=1.",
  },
  {
    id: "cmp-3",
    topic: "comparators",
    kind: "mcq",
    question: "Порівняння починають зі старшого розряду, бо…",
    options: [
      "так простіше розводити плату",
      "перша нерівність вже вирішує, хто більший",
      "молодший біт завжди важливіший",
      "XOR не працює на LSB",
    ],
    correct: 1,
    explain: "Вага MSB найбільша. Якщо A3≠B3, молодші біти вже не змінять знак нерівності.",
  },
  {
    id: "cmp-4",
    topic: "comparators",
    kind: "mcq",
    question: "A=0010, B=0011. Що активне?",
    options: ["A>B", "A=B", "A<B", "усі три"],
    correct: 2,
    explain: "2 < 3. Різниця в LSB: A0=0, B0=1.",
  },
  {
    id: "cmp-5",
    topic: "comparators",
    kind: "mcq",
    question: "Скільки з трьох виходів gt/eq/lt одночасно =1 у справного компаратора?",
    options: ["завжди 3", "рівно 1", "0 або 2", "будь-яка кількість"],
    correct: 1,
    explain: "Стани взаємовиключні: число або більше, або рівне, або менше.",
  },
  {
    id: "add-1",
    topic: "adders",
    kind: "bits",
    question: "Напівсуматор, A=1, B=1. Виходи S і C?",
    labels: ["S", "C"],
    correct: [0, 1],
    explain: "1+1 = 10₂: сума 0, перенесення 1. S=A⊕B, C=A·B.",
  },
  {
    id: "add-2",
    topic: "adders",
    kind: "bits",
    question: "Повний суматор, A=1, B=1, Cin=1. S і Cout?",
    labels: ["S", "Cout"],
    correct: [1, 1],
    explain: "1+1+1 = 11₂. Сума 1, перенесення 1.",
  },
  {
    id: "add-3",
    topic: "adders",
    kind: "bits",
    question: "4-бітовий суматор: 0101 + 0011, Cin=0. Сума S3…S0 (без Cout)?",
    labels: ["S3", "S2", "S1", "S0"],
    correct: [1, 0, 0, 0],
    explain: "5+3=8, тобто 1000. Cout=0.",
  },
  {
    id: "add-4",
    topic: "adders",
    kind: "mcq",
    question: "Чим повний суматор відрізняється від напівсуматора?",
    options: [
      "немає виходу суми",
      "має вхід Cin",
      "працює лише на 4 біти",
      "не має перенесення",
    ],
    correct: 1,
    explain: "Повний суматор додає третій біт — перенесення з молодшого розряду.",
  },
  {
    id: "add-5",
    topic: "adders",
    kind: "mcq",
    question: "1111 + 0001 на 4 бітах дає Cout=…",
    options: ["0", "1", "X", "той самий, що S"],
    correct: 1,
    explain: "15+1=16. У 4 бітах сума 0000, одиниця виходить у Cout.",
  },
  {
    id: "mux-1",
    topic: "mux",
    kind: "mcq",
    question: "MUX 4:1, S1S0=10. На вихід Y проходить…",
    options: ["I0", "I1", "I2", "I3"],
    correct: 2,
    explain: "10₂ = 2, отже Y = I2.",
  },
  {
    id: "mux-2",
    topic: "mux",
    kind: "mcq",
    question: "Скільки селекторів у MUX 8:1?",
    options: ["2", "3", "8", "1"],
    correct: 1,
    explain: "2ⁿ входів потребують n селекторів. 8=2³ → 3 лінії S.",
  },
  {
    id: "mux-3",
    topic: "mux",
    kind: "bits",
    question: "I = {I0=1, I1=0, I2=1, I3=0}, S=01. Y?",
    labels: ["Y"],
    correct: [0],
    explain: "S=01 обирає I1, а I1=0.",
  },
  {
    id: "mux-4",
    topic: "mux",
    kind: "mcq",
    question: "MUX можна використати як LUT, бо…",
    options: [
      "він завжди додає біти",
      "селектори — змінні, входи — значення функції",
      "він має памʼять",
      "вихід завжди 1",
    ],
    correct: 1,
    explain: "Таблицю істинності «зашивають» у Ii, аргументи подають на S.",
  },
  {
    id: "mux-5",
    topic: "mux",
    kind: "mcq",
    question: "Якщо строб Enable=0 (активний 1), типовий MUX на Y видає…",
    options: ["обраний Ii", "0", "1", "інверсію S"],
    correct: 1,
    explain: "Вимкнений корпус не пускає дані на шину: Y=0 (або Z, якщо 3-state).",
  },
  {
    id: "demux-1",
    topic: "demux",
    kind: "bits",
    question: "DEMUX 1:4, D=1, S1S0=01. Y0 Y1 Y2 Y3?",
    labels: ["Y0", "Y1", "Y2", "Y3"],
    correct: [0, 1, 0, 0],
    explain: "Дані йдуть лише на вихід з номером 1.",
  },
  {
    id: "demux-2",
    topic: "demux",
    kind: "mcq",
    question: "Якщо D=0, виходи демультиплексора…",
    options: ["усі 1", "усі 0", "копія селектора", "інверсія селектора"],
    correct: 1,
    explain: "Y[S]=D=0, решта теж 0. Селектор обирає місце, але передавати нічого.",
  },
  {
    id: "demux-3",
    topic: "demux",
    kind: "mcq",
    question: "Відмінність DEMUX від дешифратора?",
    options: [
      "DEMUX не має селекторів",
      "у DEMUX на обраний вихід іде D, у дешифратора — завжди 1 (при E=1)",
      "дешифратор має памʼять",
      "немає відмінності",
    ],
    correct: 1,
    explain: "Дешифратор = DEMUX із D=1. Дані в дешифраторі фіксовані.",
  },
  {
    id: "demux-4",
    topic: "demux",
    kind: "mcq",
    question: "DEMUX 1:8 потребує селекторів…",
    options: ["1", "2", "3", "8"],
    correct: 2,
    explain: "8 виходів = 2³, отже 3 лінії адреси.",
  },
  {
    id: "demux-5",
    topic: "demux",
    kind: "bits",
    question: "D=1, S=11 (1:4). Виходи Y0…Y3?",
    labels: ["Y0", "Y1", "Y2", "Y3"],
    correct: [0, 0, 0, 1],
    explain: "11₂ = 3, активний Y3.",
  },
];

export function tasksFor(topic: TopicId): Task[] {
  return TASKS.filter((t) => t.topic === topic);
}

export function examSet(): Task[] {
  const out: Task[] = [];
  const byTopic = new Map<TopicId, Task[]>();
  for (const t of TASKS) {
    const list = byTopic.get(t.topic) ?? [];
    list.push(t);
    byTopic.set(t.topic, list);
  }
  for (const list of byTopic.values()) {
    const pick = list[Math.floor(Math.random() * list.length)];
    if (pick) out.push(pick);
  }
  return out;
}
