/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as LabTopicIdRouteImport } from './routes/lab.$topicId'
import { Route as TeacherGroupIdRouteImport } from './routes/teacher.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTopicIdRoute = LabTopicIdRouteImport.update({
  id: '/lab/$topicId',
  path: '/lab/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherGroupIdRoute = TeacherGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/lab/$topicId': typeof LabTopicIdRoute
  '/teacher/$groupId': typeof TeacherGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/lab/$topicId': typeof LabTopicIdRoute
  '/teacher/$groupId': typeof TeacherGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/lab/$topicId': typeof LabTopicIdRoute
  '/teacher/$groupId': typeof TeacherGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/practice'
    | '/teacher'
    | '/lab/$topicId'
    | '/teacher/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/practice'
    | '/teacher'
    | '/lab/$topicId'
    | '/teacher/$groupId'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/login'
    | '/practice'
    | '/teacher'
    | '/lab/$topicId'
    | '/teacher/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  LabTopicIdRoute: typeof LabTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$topicId': {
      id: '/lab/$topicId'
      path: '/lab/$topicId'
      fullPath: '/lab/$topicId'
      preLoaderRoute: typeof LabTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$groupId': {
      id: '/teacher/$groupId'
      path: '/$groupId'
      fullPath: '/teacher/$groupId'
      preLoaderRoute: typeof TeacherGroupIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherRouteChildren {
  TeacherGroupIdRoute: typeof TeacherGroupIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherGroupIdRoute: TeacherGroupIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  TeacherRoute: TeacherRouteWithChildren,
  LabTopicIdRoute: LabTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
